# Generated by Django 4.2.5 on 2023-11-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_remove_categoria_nombrecategoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nombreCategoria',
            field=models.CharField(default='nombre', max_length=155),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipoCategoria',
            field=models.CharField(choices=[('sabor', 'Sabor'), ('dieta', 'Dieta')], default='sin Categoria', max_length=20),
        ),
    ]
