# Generated by Django 4.2.5 on 2023-11-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0003_categoria_nombrecategoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='nombreCategoria',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='tipoCategoria',
        ),
        migrations.AddField(
            model_name='categoria',
            name='categoriaDieta',
            field=models.CharField(choices=[('dieta', 'Dieta')], default='sin Categoria', max_length=20),
        ),
        migrations.AddField(
            model_name='categoria',
            name='categoriaSabor',
            field=models.CharField(choices=[('sabor', 'Sabor')], default='sin Categoria', max_length=20),
        ),
    ]
