# Generated by Django 4.2.5 on 2023-11-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0004_remove_categoria_nombrecategoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nombreCategoriaDieta',
            field=models.CharField(default='nombre', max_length=155),
        ),
        migrations.AddField(
            model_name='categoria',
            name='nombreCategoriaSabor',
            field=models.CharField(default='nombre', max_length=155),
        ),
    ]
