# Generated by Django 4.2.5 on 2023-11-23 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0005_categoria_nombrecategoriadieta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoCategoria1', models.CharField(choices=[('sabor', 'Sabor'), ('dieta', 'Dieta')], default='sin Categoria', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='nombreCategoriaDieta',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='nombreCategoriaSabor',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='categoriaDieta',
            field=models.ForeignKey(choices=[('mediterranea', 'Mediterranea'), ('vegetariana', 'Vegetariana'), ('Vegana', 'Vegana'), ('cetogénica', 'Cetogénica')], default='sin Categoria', max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_dieta', to='categoria.tipocategoria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='categoriaSabor',
            field=models.ForeignKey(choices=[('dulce', 'Dulce'), ('salado', 'Salado'), ('amargo', 'Amargo'), ('ácido', 'Ácido'), ('picante', 'Picante')], default='sin Categoria', max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_sabor', to='categoria.tipocategoria'),
        ),
    ]
