# Generated by Django 4.2.5 on 2023-11-23 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0006_tipocategoria_remove_categoria_nombrecategoriadieta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoriaDieta',
            field=models.ForeignKey(choices=[('mediterranea', 'Mediterranea'), ('vegetariana', 'Vegetariana'), ('Vegana', 'Vegana'), ('cetogénica', 'Cetogénica')], default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_dieta', to='categoria.tipocategoria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='categoriaSabor',
            field=models.ForeignKey(choices=[('dulce', 'Dulce'), ('salado', 'Salado'), ('amargo', 'Amargo'), ('ácido', 'Ácido'), ('picante', 'Picante')], default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_sabor', to='categoria.tipocategoria'),
        ),
    ]
