# Generated by Django 4.2.5 on 2023-11-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0007_alter_categoria_categoriadieta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('categoriaDieta', models.CharField(choices=[('mediterranea', 'Mediterranea'), ('vegetariana', 'Vegetariana'), ('Vegana', 'Vegana'), ('cetogénica', 'Cetogénica')], default=1, max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='categoriaDieta',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='categoriaSabor',
            field=models.CharField(choices=[('dulce', 'Dulce'), ('salado', 'Salado'), ('amargo', 'Amargo'), ('ácido', 'Ácido'), ('picante', 'Picante')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='tipoCategoria',
        ),
    ]
