# Generated by Django 4.2.5 on 2023-11-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0008_categoriadieta_remove_categoria_categoriadieta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='categoriadieta',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
