# Generated by Django 4.2.5 on 2023-11-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0009_alter_categoria_descripcion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriaDieta',
        ),
    ]
