# Generated by Django 3.2 on 2023-11-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0011_categoriadieta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriadieta',
            name='categoriaDieta',
            field=models.CharField(choices=[('mediterranea', 'Mediterranea'), ('vegetariana', 'Vegetariana'), ('Vegana', 'Vegana'), ('cetogénica', 'Cetogénica'), ('carnivoro', 'Carnivoro')], max_length=20),
        ),
    ]
