# Generated by Django 3.2 on 2023-12-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0012_alter_categoriadieta_categoriadieta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoriaSabor',
            field=models.CharField(choices=[('dulce', 'Dulce'), ('salado', 'Salado'), ('amargo', 'Amargo'), ('ácido', 'Ácido'), ('picante', 'Picante')], default='dulce', max_length=20),
        ),
    ]
