# Generated by Django 4.2.5 on 2023-11-23 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingredientes', '0002_ingredientes_categoria_ingredientes_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientes',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='ingredientes',
            name='producto',
        ),
        migrations.AddField(
            model_name='ingredientes',
            name='vendedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to=settings.AUTH_USER_MODEL),
        ),
    ]
