# Generated by Django 4.2.5 on 2023-11-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0003_remove_ingredientes_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientes',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
