# Generated by Django 4.2.5 on 2023-11-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0004_ingredientes_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientes',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
