# Generated by Django 4.2.5 on 2023-11-24 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0005_alter_ingredientes_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientes',
            name='cantidad',
        ),
    ]
