# Generated by Django 4.2.5 on 2023-11-16 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0001_initial'),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='nombre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='compra_nombre', to='ingredientes.ingredientes'),
        ),
        migrations.AddField(
            model_name='compra',
            name='precio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='compra_precio', to='ingredientes.ingredientes'),
        ),
    ]
