# Generated by Django 3.2 on 2023-12-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_auto_20231202_2102'),
        ('compras', '0003_compra_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='compra',
        ),
        migrations.AddField(
            model_name='compra',
            name='carrito',
            field=models.ManyToManyField(to='carrito.Carrito'),
        ),
    ]
