# Generated by Django 3.2 on 2023-12-05 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0006_remove_ingredientes_cantidad'),
        ('compras', '0004_auto_20231204_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='precio',
        ),
        migrations.AddField(
            model_name='compra',
            name='Id_ingredientes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_compra', to='ingredientes.ingredientes'),
        ),
    ]
