# Generated by Django 3.2 on 2023-12-05 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_alter_compra_carrito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='carrito',
            new_name='Id_carrito',
        ),
    ]
