# Generated by Django 3.2 on 2023-12-05 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_auto_20231205_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='Id_carrito',
            new_name='carrito',
        ),
    ]
