# Generated by Django 3.2 on 2023-12-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0012_auto_20231205_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='Id_carrito',
        ),
    ]
