# Generated by Django 4.2.5 on 2023-11-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='region',
            field=models.CharField(choices=[('aguascalientes', 'Aguascalientes'), ('baja_california', 'Baja California'), ('baja_california_sur', 'Baja California Sur'), ('campeche', 'Campeche'), ('coahuila', 'Coahuila'), ('colima', 'Colima'), ('chiapas', 'Chiapas'), ('chihuahua', 'Chihuahua'), ('ciudad_de_mexico', 'Ciudad de México'), ('durango', 'Durango'), ('guanajuato', 'Guanajuato'), ('guerrero', 'Guerrero'), ('hidalgo', 'Hidalgo'), ('jalisco', 'Jalisco'), ('estado_de_mexico', 'Estado de México'), ('michoacan', 'Michoacán'), ('morelos', 'Morelos'), ('nayarit', 'Nayarit'), ('nuevo_leon', 'Nuevo León'), ('oaxaca', 'Oaxaca'), ('puebla', 'Puebla'), ('queretaro', 'Querétaro'), ('quintana_roo', 'Quintana Roo'), ('san_luis_potosi', 'San Luis Potosí'), ('sinaloa', 'Sinaloa'), ('sonora', 'Sonora'), ('tabasco', 'Tabasco'), ('tamaulipas', 'Tamaulipas'), ('tlaxcala', 'Tlaxcala'), ('veracruz', 'Veracruz'), ('yucatan', 'Yucatán'), ('zacatecas', 'Zacatecas')], default='México', max_length=20),
        ),
    ]
