# Generated by Django 4.2.5 on 2023-11-24 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0011_categoriadieta'),
        ('ingredientes', '0006_remove_ingredientes_cantidad'),
        ('productos', '0004_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoriaD',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categoria.categoriadieta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ingredientes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ingredientes.ingredientes'),
        ),
    ]
