# Generated by Django 4.2.5 on 2023-11-24 18:03

from django.db import migrations, models
import ingredientes.models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_remove_producto_ingredientes_producto_ingredientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ingredientes',
        ),
        migrations.AddField(
            model_name='producto',
            name='ingredientes',
            field=models.BooleanField(default=1, verbose_name=ingredientes.models.Ingredientes),
        ),
    ]
