# Generated by Django 4.2.5 on 2023-11-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0006_remove_ingredientes_cantidad'),
        ('productos', '0007_remove_producto_ingredientes_producto_ingredientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ingredientes',
        ),
        migrations.AddField(
            model_name='producto',
            name='ingredientes',
            field=models.ManyToManyField(to='ingredientes.ingredientes'),
        ),
    ]
