# Generated by Django 3.2 on 2023-11-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_remove_producto_ingredientes_producto_ingredientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imgProducto',
            field=models.ImageField(null=True, upload_to='imgProductos'),
        ),
    ]
