# Generated by Django 4.2.5 on 2023-11-19 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_remove_usuario_tipousuario_usuario_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_staff',
        ),
    ]
