# Generated by Django 4.2.5 on 2023-11-19 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_remove_usuario_is_active_remove_usuario_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='tipo_usuario',
            new_name='tipoUsuario',
        ),
    ]
