# Generated by Django 4.2.5 on 2023-11-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_rename_tipo_usuario_usuario_tipousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Usuario Cliente'), ('vendedor', 'Vendedor')], default='cliente', max_length=20),
        ),
    ]
