# Generated by Django 4.2.5 on 2023-11-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Cliente'), ('vendedor', 'Vendedor')], default='cliente', max_length=20),
        ),
    ]
