# Generated by Django 4.2.5 on 2023-11-22 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_alter_usuario_tipousuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='email',
            new_name='username',
        ),
    ]
