# Generated by Django 4.2.5 on 2023-11-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_rename_username_usuario_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_staff',
        ),
    ]
