# Generated by Django 3.2 on 2023-12-01 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0006_remove_ingredientes_cantidad'),
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='Id_ingredientes',
        ),
        migrations.AddField(
            model_name='carrito',
            name='Id_ingredientes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ingredientes.ingredientes'),
        ),
    ]
