# Generated by Django 4.2.5 on 2023-11-16 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0002_ingredientes_categoria_ingredientes_producto'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='Id_Ingrediente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ingredientes.ingredientes'),
        ),
    ]
