# Generated by Django 4.2.5 on 2023-11-24 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_inventario_id_ingrediente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='Id_Ingrediente',
            new_name='nombreIngrediente',
        ),
    ]
