# Generated by Django 4.2.5 on 2023-11-24 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_rename_id_ingrediente_inventario_nombreingrediente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='nombreIngrediente',
            new_name='nombreIngredienteInv',
        ),
    ]
